#!/bin/bash
# Quick Start Guide
# This script provides easy commands for common tasks

echo "🚀 First2Apply Quick Start Guide"
echo "================================"
echo ""

echo "📋 Available Commands:"
echo ""
echo "🔧 Environment Setup:"
echo "  npm run dev:setup           # One-time developer setup"
echo ""
echo "🚀 Run Applications:"
echo "  npm run dev:start           # Start development environment"
echo "  npm run prod:start          # Start production-like environment"
echo ""
echo "📱 Individual App Commands:"
echo "  cd webapp && npm run dev   # Start webapp"
echo "  cd desktopProbe && npm start # Start desktop app"
echo ""
echo "🔍 Verification:"
echo "  supabase status            # Check Supabase status"
echo "  cat webapp/.env.local      # Check webapp environment"
echo "  cat desktopProbe/.env      # Check desktopProbe environment"
echo ""
echo "📖 Documentation:"
echo "  cat README.md               # Canonical guide"
echo ""
echo "🎯 Quick Start Examples:"
echo ""
echo "1. Start Development (Local Database):"
echo "   npm run dev:start"
echo "   # Then in separate terminals:"
echo "   cd webapp && npm run dev"
echo "   cd desktopProbe && npm start"
echo ""
echo "2. Start Production (Cloud Database):"
echo "   npm run prod:start"
echo "   # Then in separate terminals:"
echo "   cd webapp && npm run dev"
echo "   cd desktopProbe && npm start"
echo ""
echo "3. Switch Between Modes:"
echo "   npm run dev:setup         # Ensure dev env is prepared"
echo ""
echo "⚠️  Important Notes:"
echo "   - Development: Safe local database, good for testing"
echo "   - Production: Real data (2,382 jobs), requires authentication"
echo "   - Always check which mode you're in before making changes!"
echo ""
echo "🎉 Ready to start? Run: npm run dev:start or npm run prod:start"


