import { Navbar } from '@/components/navbar';
import { ThemeProvider } from '@/components/themeProvider';
import { Toaster } from '@/components/ui/toaster';
import { AppStateProvider } from '@/hooks/appState';
import { LinksProvider } from '@/hooks/links';
import { SessionProvider } from '@/hooks/session';
import { SettingsProvider } from '@/hooks/settings';
import { SitesProvider } from '@/hooks/sites';
import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'First 2 Apply',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      </head>
      <body className={`antialiased`}>
        <>
          <AppStateProvider>
            <SessionProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                // defaultTheme={"light"}
                disableTransitionOnChange
              >
                <SettingsProvider>
                  <SitesProvider>
                    <LinksProvider>
                      <div className="scroll-smooth md:h-screen md:overflow-y-scroll">
                        <Navbar />
                        {/* The padding ensures content is never hidden behind the navbar.
                        Even if the navbar is conditionally hidden (e.g., when logged out),
                        we keep the padding to prevent unexpected layout shifts when it appears. */}
                        <main className="mx-auto min-h-screen max-w-[1536px] p-4 pb-[72px] md:p-5 md:pt-[76px]">
                          {children}
                        </main>
                      </div>
                    </LinksProvider>
                  </SitesProvider>
                </SettingsProvider>
              </ThemeProvider>
            </SessionProvider>
          </AppStateProvider>

          <Toaster />
        </>
      </body>
    </html>
  );
}
