import { Navbar } from '@/components/navbar';
import { ThemeProvider } from '@/components/themeProvider';
import { Toaster } from '@/components/ui/toaster';
import { AppStateProvider } from '@/hooks/appState';
import { LinksProvider } from '@/hooks/links';
import { SessionProvider } from '@/hooks/session';
import { SettingsProvider } from '@/hooks/settings';
import { SitesProvider } from '@/hooks/sites';
import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'First 2 Apply',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <>
          <AppStateProvider>
            <SessionProvider>
              <ThemeProvider
                attribute="class"
                system={true}
                defaultTheme="system"
                // defaultTheme={"light"}
                disableTransitionOnChange
              >
                <SettingsProvider>
                  <SitesProvider>
                    <LinksProvider>
                      {/* Layout for logged in user */}
                      <div className="scroll-smooth pb-16 md:h-screen md:overflow-y-scroll md:pb-0">
                        <Navbar />
                        <main className="mx-auto min-h-screen max-w-[1536px] p-4 md:p-5">{children}</main>
                      </div>
                    </LinksProvider>
                  </SitesProvider>
                </SettingsProvider>
              </ThemeProvider>
            </SessionProvider>
          </AppStateProvider>

          <Toaster />
        </>
      </body>
    </html>
  );
}
